export enum FONT_FAMILY {
  MontserratBlack = 'Montserrat-Black',
  MontserratBlackItalic = 'Montserrat-BlackItalic',
  MontserratBold = 'Montserrat-Bold',
  MontserratBoldItalic = 'Montserrat-BoldItalic',
  MontserratExtraBold = 'Montserrat-ExtraBold',
  MontserratExtraBoldItalic = 'Montserrat-ExtraBoldItalic',
  MontserratExtraLight = 'Montserrat-ExtraLight',
  MontserratExtraLightItalic = 'Montserrat-ExtraLightItalic',
  MontserratItalic = 'Montserrat-Italic',
  MontserratLight = 'Montserrat-Light',
  MontserratLightItalic = 'Montserrat-LightItalic',
  MontserratMedium = 'Montserrat-Medium',
  MontserratMediumItalic = 'Montserrat-MediumItalic',
  MontserratRegular = 'Montserrat-Regular',
  MontserratSemiBold = 'Montserrat-SemiBold',
  MontserratSemiBoldItalic = 'Montserrat-SemiBoldItalic',
  MontserratThin = 'Montserrat-Thin',
  MontserratThinItalic = 'Montserrat-ThinItalic',
}
